### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by Kushagraw12** [insidesherpa/JPMC-tech-task-1-PY3#35]
When i type python3 client3.py cmd give me no response.  
![Screenshot (15)](https://user-images.githubusercontent.com/53997603/80289092-03df6580-875a-11ea-9629-a527ca2ed160.png)

**Comment by Pradhuyamn** [comment]
A similar  Issue can't open file server.py and client.py
![Screenshot (189)](https://user-images.githubusercontent.com/50438977/80591835-fff26280-8a3b-11ea-9374-2c0579f8a221.png)
![Screenshot (190)](https://user-images.githubusercontent.com/50438977/80591839-01bc2600-8a3c-11ea-8b93-8db1a6229810.png)

**Comment by aholley30** [comment]
@Pradhuyamn Are you sure you have python3 installed? Because python3 server3.py should work. Try running python3 -V in the command prompt, and it should tell you the version of python3 you have if you have it.

@Kushuboi Maybe try adding -v to the end of your statements, so it'd be python3 server3.py -v. This should make the outputs verbose so maybe you'd be able to see the hidden errors you're getting.

**Comment by Sid1808-dev** [comment]
simply try and use the command python client3.py and python server3.py

**Comment by Kushagraw12** [comment]
Thanks everyone! Trying  `py server3.py`  workerd for me!
