### ISSUE TITLE
I am successfully able to run the server3.py on my terminal with administrator access but the client.py is giving error 

### ISSUE THREAD

**Issue by shobitgg** [insidesherpa/JPMC-tech-task-1-PY3#94]
I am successfully able to run the server3.py on my terminal with administrator access but the client.py is giving error 

![server](https://user-images.githubusercontent.com/41900814/82323078-27ae6800-99f5-11ea-994f-15fb9af0529e.PNG)
![client](https://user-images.githubusercontent.com/41900814/82323085-2aa95880-99f5-11ea-882c-f30c1e6d5760.PNG)

**Comment by dheerajodha** [comment]
Hi @shobitgg I'm not sure about Windows since I use Linux, however it's worth trying to shift your project to a directory which doesn't has space anywhere in its path, for example, your path has lots of spaces, ie. VIT [space]EDUC, JP[space]MORGAN[space]VIRTUAL etc.

Try making a new folder inside "shobhit" such that it's name doesn't have a space, and then clone project inside that folder and repeat the steps again.

I'm not sure if this would work or not, but I've seen that in Windows some of the error is caused by this reason. or maybe try and run "python3 client3.py"

If you get some more errors, then post your error screenshots here.
If you've already solved your issue, please close this issue, thanks!

**Comment by shobitgg** [comment]
Thank you for the reply! but i generally dont consider the path to be a problem but still i tried according to your suggestion of changing path to shobit/....


but im getting a error again but its different error now in client3.py
i have py-3.5 and usng python client3.py command only works in my system as it is configured as such (python instead of python3) and python3 client3.py doent work.

Im not understanding the issue still getting an error.Should thsi be doen in the online repl compiler or can also be done of the local system (own system).
![clint](https://user-images.githubusercontent.com/41900814/82431700-9f8b9980-9aac-11ea-90eb-4aab90f793dd.PNG)

**Comment by dheerajodha** [comment]
Just to confirm, I hope you have **first** started your server in **another CMD** by running command "python server3.py" (or whichever command works in your case) AND after that you opened another CMD inside the same location **and** **then** executed "python client3.py" ?

**Comment by shobitgg** [comment]
Yes :) i have first started server and it is working fine
CMD1-admin access
![server1](https://user-images.githubusercontent.com/41900814/82436261-29d6fc00-9ab3-11ea-9afb-f21111e609d6.PNG)

server is given admin access as well
but client has error.client is NOT given admin access as mentioned.

CMD2 -NO Admin access

![client 1](https://user-images.githubusercontent.com/41900814/82436368-5723aa00-9ab3-11ea-9f20-cdee532fcebb.PNG)

**Comment by dheerajodha** [comment]
@shobitgg The dev setup guide clearly mentions :
**any python 3.x >= 3.6is fine, latest is recommended (3.8.0)**

As you said, you are using Python 3.5 
It's possible that you're getting this error because you don't have minimum required python version, look here : https://stackoverflow.com/a/55162221

**Comment by MThakkar121** [comment]
Just do one thing try to change the port number that you've given in code and then try to run both parallely...

**Comment by shobitgg** [comment]
> @shobitgg The dev setup guide clearly mentions :
> **any python 3.x >= 3.6is fine, latest is recommended (3.8.0)**
> 
> As you said, you are using Python 3.5
> It's possible that you're getting this error because you don't have minimum required python version, look here : https://stackoverflow.com/a/55162221

**Comment by shobitgg** [comment]
I changed to python 3.8 recent version and everything worked fine with the previous issue.Thank you for your help @dheerajodha @MThakkar121
